---
title: "Introduction to R -- Workshop Home"
output: 
  html_document:
    toc: FALSE
---

The following learning materials support our *Introduction to R: Data Transformations, Analysis, and Data Structures* workshop.  Hosted by [Data & Visualization Services](http://library.duke.edu/) at Duke University Libraries, this is the first part of a multi-part learning series on R that we call [*R We Having Fun Yet‽*](https://rfun.library.duke.edu).  See also this [video recording](https://library.capture.duke.edu/Panopto/Pages/Viewer.aspx?id=651c273a-f1b0-485b-bf47-6bd61e304020) of a previous workshop.

This gentle introduction provides a hands-on experience to learn the basics of modern R using RStudio and the Tidyverse method.  Learn about managing your R projects, data types, variable assignments, data structures, and visualization packages such as `ggvis` and `leaflet`.  The focus of these learning resources is as a code demonstrations supporting our in-person workshop.  Thus the explanatory prose is minimal.  If you wish to read more about R, we recommend [R for Data Science](http://r4ds.had.co.nz/) and [Data Visualization for Social Science](http://socviz.co/), or the interactive course made available at [DataCamp](https://www.datacamp.com/). Attendees will be registered for the opportunity of supplementing this workshop with free academic access to [DataCamp's Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r) course. 

- [practice code](https://github.com/libjohn/intro2r-2018fall)
- [slides](https://github.com/data-and-visualization/Intro2R/tree/master/slides)

## Workshop Outline

### Housekeeping / Introduction

<!-- p class="right">Joel</p -->

1. Welcome  
2. What is r 
3. What is [RStudio](https://www.rstudio.com/) 
4. What is a Project
5. What is [Docker](https://vm-manage.oit.duke.edu/containers/rstudio)

### Data Management

<!-- p class="right">John</p -->

1. Load Data
1. View Data
1. Tidyverse:  Tibbles and Data Frames
1. Data Structures
1. Data Types

### Exercise One

<!--p class="right">Joel</p -->

- Exercise
- Quiz

### Data Wrangling

<!-- p class="right">John</p -->

#### Dplyr

- Arrange
- Select
- Filter
- Mutate
- Count 
- Summarize
- Putting it All Together

### Exercise Two

<!-- p class="right">Joel</p -->

- Exercise
- Quiz

### Visualization

<!-- p class="right">John</p -->

- ggvis

### GIS

- leaflet



