---
title: "Assignments for Intro to R Class"
author: "Joel Herndon and John Little"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    latex_engine: xelatex
fontsize: 25pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PART ONE: Loading Data

For the workshop, we've prebuilt a data set that has information about menus in Duke's new West Union from three restaurants.  

1. Using what we've you've seen in class, if `data/westUnion.csv` is a csv file, how would you load the file into a new variable called `westUnion`?

2. What data type is `westUnion`?

3. Take a look at the structure of the `westUnion` variable.
    - How many observations (rows) are there?
    - How many variables (columns) are there?
    - How many of the variables are numeric data?
    


## PART TWO: Data Management

All of the following questions are based on the sample of restaurants represented in the dataset which is accurate as of September 2, 2016.

1. Which restaurant has the lowest cost item and what is the item?

2. Which restaurant has the most expensive item(s)?  What are those item(s)?

3. At the West Union, how many of the entrees (found in the `menuType` variable) cost eight dollars?

4. The head of Duke dining is considering reducing prices at the West Union. Using what we've learned in class, write a line of code that will calculate a new variable (`halfPrice`) that contains items at half price.

5. How many entrees are in the dataset (`menuType` variable)? How many desserts 
    


